#!/usr/bin/python

import os
import subprocess
import sys

import git_lib
import utils

def RepoUpload(args):
  cmd = 'repo upload . --cbr '
  cmd += args[0] if args and args[0] == '--no-verify' else '--verify'
  utils.RunCmd(cmd, call=True)


def Update(args):
  if not git_lib.GitDiff():
    print 'Diff empty, nothing to update'
    #return

  if not utils.IsCrOS() and git_lib.GitNoCommit():
    git_lib.GitCommit()
    return

  if not utils.IsCrOS():
    git_lib.GitSetUpstream('master')
  git_lib.GitCommitFixup()
  git_lib.GitAutoSquash()


def Upload(args):
  if utils.IsCrOS():
    RepoUpload(args)
  else:
    git_lib.GitSetUpstream('origin/master')
    git_lib.GitUpload()
    git_lib.GitSetUpstream('master')


def Usage(argv):
  print 'Usage: %s [upload|update]' % argv[0].split('/')[-1]


def main(argv):
  utils.AssertCWD([utils.CROS_DIR, utils.CHROME_DIR, utils.CATAPULT_DIR])

  func_map = { 'upload': Upload, 'update': Update }
  if argv[1] not in func_map.keys():
    Usage(argv)
  else:
    func_map[argv[1]](argv[2:])


if __name__ == '__main__':
  sys.exit(main(sys.argv))
