#!/usr/bin/python

import argparse
import os
import sys

import constants
import utils


def Remote(opts, host):
  cmd = ['scp'] if opts.scp else ['ssh']
  cmd += ['-o', 'UserKnownHostsFile=/dev/null', '-o',
          'StrictHostKeyChecking=no', '-i',
          os.path.join(utils.CHROME_DIR,
                       'third_party/chromite/ssh_keys/testing_rsa')]
  if opts.forward_port:
    cmd += ['-L', '%d:localhost:%d' % (opts.forward_port, opts.forward_port)]

  if opts.vm or (opts.port != constants.VM_PORT):
    cmd += ['root@localhost', '-p', opts.port]
  else:
    cmd += ['root@%s' % opts.host]

  utils.RunCmd(cmd, call=True)


def ParseArgs(argv):
  parser = argparse.ArgumentParser('Script for SSH and SCP')
  parser.add_argument('--forward-port', type=int, help='Port to forward')
  parser.add_argument('--vm', action='store_true', default=False,
                      help='SSH into VM')
  parser.add_argument('--port', default=constants.VM_PORT,
                      help='VM port (default %s)' % constants.VM_PORT)
  parser.add_argument('--dut', action='store_true', default=False,
                      help='SSH into DUT')
  parser.add_argument('--host', default=constants.DEVICE_IP,
                      help='DUT hostname (default %s)' % constants.DEVICE_IP)
  parser.add_argument('--scp', action='store_true', default=False,
                      help='SCP instead of SSH')
  return parser.parse_known_args(argv[1:])


def main(argv):
  opts, host = ParseArgs(argv)
  Remote(opts, host)


if __name__ == '__main__':
  sys.exit(main(sys.argv))
